# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea5e38d369c8c90a6afcf68057dd7a8dcd623c9a8886103196eb0fa67bd25600ee6237c4dbced12e59947538850f405c704c794def98d0d9a2358c041246cab

test:
  secret_key_base: 8ea5e38d369c8c90a6afcf68057dd7a8dcd623c9a8886103196eb0fa67bd25600ee6237c4dbced12e59947538850f405c704c794def98d0d9a2358c041246cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8ea5e38d369c8c90a6afcf68057dd7a8dcd623c9a8886103196eb0fa67bd25600ee6237c4dbced12e59947538850f405c704c794def98d0d9a2358c041246cab